### PR TITLE
Add physical computing rs

### PR DESCRIPTION
**Pull request by rahul-thakoor**
Add link to the Physical Computing with Rust guide. It is an adapted version of the Physical Computing with Python by the Raspberry Pi Foundation.

### CODE REVIEW

**Comment by berkus** [comment]
Erm, pulling from `master`, people - why not rebase your changes prior to proposing PR??

Nitpicking, but I'd prefer to keep history clean.

**Comment by ashleygwilliams** [comment]
hey @berkus just maintainer to maintainer- please remember that some folks aren't as familiar with open source contributing as you! rebasing a PR would be a great addition to your `CONTRIBUTING.md` file (i just looked and it doesn't mention this). ad hoc messages like this can hurt and dissuade folks- and i'm sure that's not what you intend :)

**Comment by jamesmunns** [comment]
I also want to chime in that asking for a rebase is not an unreasonable request (during a review period, before the PR has already been accepted/merged), but we also need contributions much more than we need a clean git history. The code of conduct [for this project] (and rust-embedded and rust in general) calls for "Using welcoming and inclusive language", and all of us, especially maintainers, need to abide by that. Please feel free to contact me privately if you have any questions.

[for this project]: https://github.com/rust-embedded/awesome-embedded-rust/blob/master/Code-of-Conduct.md#our-standards

Lets focus on teaching, rather than criticism.

**Comment by berkus** [comment]
@ashleygwilliams thanks, that makes sense, I will look at updating the `CONTRIBUTING.md`.

Did not mean to criticize the work of anyone.

**Pull request merged**
