### PR TITLE
Add project rainbow-hat-rs for support of the Pimoroni Rainbow HAT board

### PR DESCRIPTION
**Pull request by yannart**
GitHub repo: https://github.com/yannart/rainbow-hat-rs

### CODE REVIEW

**Comment by adamgreig** [comment]
Thanks for this PR! It looks like this should probably go in the "drivers" section rather than the "board support crates" section though - the BSCs are more for development boards with a microcontroller on, rather than peripherals like this rainbow HAT.

Do note that the drivers section asks for a short blog post (or gist or something) to show off using the driver, unless it goes in the "work in progress" section.

**Comment by yannart** [comment]
Thanks @adamgreig for your comment. I have moved to the "drivers" section. I have included a link to the README file of the repo that contains a description and examples. Let me know if that is sufficient or you want me to move to WIP.

**Review by adamgreig — APPROVED** [review]
Thanks!

bors merge

**Comment by yannart** [comment]
Awesome, thanks!

**Pull request merged**
