### PR TITLE
Add several tools to list

### PR DESCRIPTION
**Pull request by Dblm0**
Tools added:
-   [cargo-bloat](https://github.com/RazrFalcon/cargo-bloat)
-   [cargo-call-stack](https://crates.io/crates/cargo-call-stack)
-   [cargo-dfu](https://crates.io/crates/cargo-dfu)

### CODE REVIEW

**Comment by burrbull** [comment]
Also `https://crates.io/crates/cargo-call-stack` should be added

**Comment by burrbull** [comment]
and `https://crates.io/crates/cargo-dfu`

**Comment by eldruin** [comment]
Thanks!
Could you move it together with the rest of cargo tools higher up in the list?
Also it would be great if you would add the tools @burrbull linked. Here is a snippet:
```suggestion
- [cargo-call-stack](https://crates.io/crates/cargo-call-stack) Static, whole program stack usage analyzer.
- [cargo-dfu](https://crates.io/crates/cargo-dfu) Cargo extension for flashing embedded rust programs via DFU.
```

**Review by eldruin — APPROVED** [review]
Looks good to me, thank you!
bors r+

**Pull request merged**
