### PR TITLE
Add Simplified Embedded Rust Book Links

### PR DESCRIPTION
**Pull request by apollolabsdev**
The update entails adding links to both editions of the Simplified Embedded Rust book as an additional resource.

### CODE REVIEW

**Comment by Inspirati** [comment]
As these resources are payware only, I suggest these links are spam and should not be included in this respository.

**Comment by jamesmunns** [comment]
"Spam" seems a little strong, but we don't generally have listing for commercially available items like paid books or videos.

We do have links to paid trainings, though all current cases are linking to public material of the paid trainings. I'll note that we should probably discuss this in the next weekly meeting.

**Comment by apollolabsdev** [comment]
I understand the concerns raised about linking to paid resources. I was initially skeptical as well, so I carefully reviewed the contribution guidelines before submitting the pull request. I did not find any explicit restriction against paid resources, which is why I proceeded.

@jamesmunns I appreciate the suggestion to discuss this in the next weekly meeting. If paid resources were to be considered and since they might not be as accessible, maybe some criteria for assessment can be introduced. Depending on the decision, it might be worth raising the point to clarify the guidelines on this matter to ensure consistency in contributions.

@Inspirati, I respectfully disagree with this position. Its equivalent to saying that that all freeware is non-spam. While there are many excellent free resources available, there are also paid resources that provide value and quality. My point is that spam can take different forms, is certainly non-desirable, and should be avoided at all costs. Ultimately, the goal should be to include resources that are genuinely beneficial to the community. Nevertheless, it's fair to consider that paid resources might be viewed as advertising and not desirable under community guidelines.

**Comment by BartMassey** [comment]
One possible compromise here is to include a separate "commercial" category in AER. As @jamesmunns suggested, we should discuss this at the next meeting.

**Comment by jamesmunns** [comment]
@apollolabsdev I'm closing this in favor of https://github.com/rust-embedded/awesome-embedded-rust/pull/455, which adds a separate paid section. I have merged your commit into that PR.

**Pull request closed without merging**
