### PR TITLE
Note null-terminated crate

### PR DESCRIPTION
**Pull request by strake**
It's a crate of generic null-terminated arrays. I find it quite useful dealing with the C world in particular.

### CODE REVIEW

**Comment by strake** [comment]
https://github.com/strake/null-terminated.rs

**Comment by RandomInsano** [comment]
This is outside of the Rust Embedded and more just crate etiquette in general: A readme and some examples would help folks understand why they would want to use your crate as well!

I’m excited to see the rationale behind why these helper functions exist and what problems they solve. I can’t quite tell from the code itself.

**Comment by strake** [comment]
I have examples and such in the docs. Alas, docs.rs failed to build the crate as it was using too old rustc. I [notified](https://github.com/onur/docs.rs/issues/23#issuecomment-424916333) and will follow up here.

**Comment by mathk** [comment]
Ping from triage: I propose that this should be part of the [showcase](https://github.com/rust-embedded/wg/blob/master/rfcs/0187-embedded-rust-showcase.md) first and close this PR ? @therealprof @RandomInsano objection?

**Comment by Disasm** [comment]
Ping from triage: @therealprof crates.io page now [contains](https://crates.io/crates/null-terminated) a link to the repo as well as docs, but description text is still far from detailed and examples are difficult to find.
@strake Could you improve the crate description and add some examples to the crate-level docs so they can be easily found?

**Comment by strake** [comment]
Brief status report: this is on my agenda; it's been a busy few weeks. I'll try to find examples for more of the API.

**Comment by strake** [comment]
Wrote more docs and examples. PTAL

**Comment by strake** [comment]
PTAL — docs not yet (as of writing this) generated, but README up on crates.io.

**Comment by berkus** [comment]
@therealprof pls review again!

**Pull request merged**
