### PR TITLE
Add VEML7700 embedded HAL driver to README.md

### PR DESCRIPTION
**Pull request by no111u3**
Add stable alternative version for VEML7700 hal drivers

### CODE REVIEW

**Comment by eldruin** [comment]
That driver is mostly my veml6030 driver with some modifications but you have removed the MIT license and my copyright replacing it with yours.
This is not acceptable.
Compare for example [this file](https://github.com/eldruin/veml6030-rs/blob/master/src/device_impl.rs) and [this file](https://github.com/no111u3/veml7700/blob/5dd943c19fb2d42f6c1bd0caf589717e974496f5/src/device_impl.rs)

**Comment by no111u3** [comment]
> That driver is mostly my veml6030 driver with some modifications but you have removed the MIT license and my copyright replacing it with yours.
> Doing this is not acceptable.
> Compare for example [this file](https://github.com/eldruin/veml6030-rs/blob/master/src/device_impl.rs) and [this file](https://github.com/no111u3/veml7700/blob/5dd943c19fb2d42f6c1bd0caf589717e974496f5/src/device_impl.rs)

Fixed this copyright issues in 0.1.6 version for crate.

**Comment by eldruin** [comment]
Thank you for the prompt copyright attribution / license fix.

Now regarding this PR, in order to add a driver the the released section a requirement is adding an introductory blog post offering a higher level explanation of how to use the driver and so on.
Some times in the past we have forgotten checking on this but this is better for newcomers.
Could you add something like that?
Alternatively, there is no such requirement for the WIP section.

**Comment by no111u3** [comment]
@eldruin thank you for clarification of rules. also I have plans to publish some article at about next week.

**Comment by no111u3** [comment]
Update: crate temporary moved to WIP (I hate my site provider).

**Review by eldruin — APPROVED** [review]
Looks good to me, thanks!
bors r+

**Pull request merged**
