### PR TITLE
Add embedded-hal-compat

### PR DESCRIPTION
**Pull request by ryankurte**
I build a little forward/reverse compatibility layer to run drivers across different HAL versions, there's probably plenty of room for improvement but already finding it pretty useful.

### CODE REVIEW

**Review by eldruin — APPROVED** [review]
LGTM. Thanks!

bors r+

**Comment by eldruin** [comment]
bors retry

**Comment by eldruin** [comment]
ugh, travis...

**Comment by adamgreig** [comment]
lol, the travis does nothing, this will be the easiest fix ever, one sec

**Comment by eldruin** [comment]
Let's retry after the swap to GHA

bors retry

**Pull request merged**
