### PR TITLE
Add the `irq` crate

### PR DESCRIPTION
**Pull request by jonas-schievink**

### CODE REVIEW

**Comment by jonas-schievink** [comment]
bors does not check reviews for commands, only normal comments

**Comment by adamgreig** [comment]
I'm sure bors does or used to check review comments for commands, it's how I've almost always r+'d PRs. Has it changed recently?

**Comment by jamesmunns** [comment]
bors r=andre-richter

**Comment by andre-richter** [comment]
Yup done it this way since a long time. Strange...

bors r+

**Comment by jonas-schievink** [comment]
Huh, weird

**Comment by jamesmunns** [comment]
If anyone is investigating, I also wonder if Github could have changed the way bors “sees” comments that originate from review comments. Ill do separate review and bors steps from now on though.

**Comment by adamgreig** [comment]
Looks like it's already filed: https://github.com/bors-ng/bors-ng/issues/855

**Pull request merged**
