### PR TITLE
Add embedded hal mock

### PR DESCRIPTION
**Pull request by eldruin**
I find this crate extremely useful when writing device crates and think it should definitely be included here.
I was not sure where to put it, though. I put it after the OS section, and before all the vendor-specific HALs but I am open to put it in any other place.
@dbrgn :)

### CODE REVIEW

**Comment by therealprof** [comment]
I agree it's extremely useful (wonder where @dbrgn got the idea from 😀). I'm a bit split whether `hal-impl` is the right place though or whether it should rather be under `Tools`.

**Comment by eldruin** [comment]
I thought of tools as well, but that sounds more like a program, and technically, it is a HAL implementation. However, I agree that it is not a HAL in the sense of the other HAL implementations, which provide access to real hardware.

**Comment by therealprof** [comment]
Tools are not necessarily programs and I think next to `µtest` in the tools section it would be in perfect company.

**Comment by eldruin** [comment]
True. I did not read the list thoroughly. I will move it next to it then.

**Comment by dbrgn** [comment]
Thanks :slightly_smiling_face:

**Pull request merged**
