### PR TITLE
add scroll

### PR DESCRIPTION
**Pull request by memoryruins**
[scroll](https://crates.io/crates/scroll): extensible and endian-aware Read/Write traits for generic containers

### CODE REVIEW

**Comment by therealprof** [comment]
@memoryruins This is nice and I don't have any objection adding it but at the moment I also can't think of any use case in embedded. Are there any projects making good use of it?

**Comment by hdhoang** [comment]
FWIW when I came across this PR, I bookmarked it to try addressing ah-/anne-key#20 with this crate :)

**Comment by therealprof** [comment]
@hdhoang Thanks for the feedback. Speaking of which, I really think we should have awesome embedded firmwares also on the list, mind submitting a PR to add anne-key? ;)

**Comment by memoryruins** [comment]
It's a core crate of https://github.com/m4b/goblin (developed by the dev of scroll), which is used in the Redox kernel. Fantastic to see anne-key already checking it out :)

**Pull request merged**
