### PR TITLE
Add infrared to the no-std crates list

### PR DESCRIPTION
**Pull request by jkristell**

### CODE REVIEW

**Comment by jkristell** [comment]
Thanks you!

**Comment by burrbull** [comment]
I tried to port arduino's irremote lib to rust, but did not complete.
Maybe it help you somehow.

https://yadi.sk/d/nWsLC2ZLpfZvBg

**Comment by jkristell** [comment]
@burrbull I did look at that library first to, and then actually settled for the same type of polling/sampling design that they use - to be as generic as possible. But for the decoding encoding I decided not to look at any other library and just try to come up with some clever by my self. I keep adding new remote control protocols by testing the ones I have at hand, I'm almost at the point now that I control all the IR enabled devices in my home :)

**Comment by jkristell** [comment]
@burrbull But I will definitely take a look later!

**Pull request merged**
