### PR TITLE
Swap to GHA

### PR DESCRIPTION
**Pull request by adamgreig**
The travis CI wasn't even doing anything, but I guess at least this means we can use bors.

### CODE REVIEW

**Review by eldruin — APPROVED** [review]
Nice! Thank you!
bors r+

**Comment by eldruin** [comment]
I guess this needs to be forcibly merged

**Comment by adamgreig** [comment]
I've just removed travis_ci as a required CI status for merges, so only bors is required now, which I would have thought should pick up the new bors.toml to allow after `dummy` passes, let's see what bors says?

**Review by eldruin — APPROVED** [review]
Initially it was still waiting for travis but now it seems gone. Let's try again.

bors r+

**Pull request merged**
