### PR TITLE
Adds embassy-start

### PR DESCRIPTION
**Pull request by huntc**
This is a link to a project starter template for writing embedded async Rust applications using Embassy.

### CODE REVIEW

**Comment by burrbull** [comment]
> The template has been derived from a number of projects that are targeting the real-world.

This phrase is good for blog. It is strange to see it here.

Better say that template is NRF based with network support.

**Comment by huntc** [comment]
> > The template has been derived from a number of projects that are targeting the real-world.
> 
> This phrase is good for blog. It is strange to see it here.

I'll move it to the "tools" section.

> 
> Better say that template is NRF based with network support.

It isn't just for nRF devices. Embassy targets a number of HALs. It isn't just for illustrating the Uarte for networking either. It is a template.

**Comment by eldruin** [comment]
Hmm, I have no strong feelings but I understand the criticism and think I would just remove this sentence, since it is implied by the previous one:
```The template has been derived from a number of projects that are targeting the real-world.```

**Comment by huntc** [comment]
> Hmm, I have no strong feelings but I understand the criticism and think I would just remove this sentence, since it is implied by the previous one:
> `The template has been derived from a number of projects that are targeting the real-world.`

Removed

**Review by eldruin — APPROVED** [review]
Thank you for all your work!
bors r+

**Pull request merged**
