### PR TITLE
Add bounded-registers to tools

### PR DESCRIPTION
**Pull request by jonlamb-gh**
For anyone curious about what bounded-registers look like, I have been hacking on a personal `bcm2711` crate in my Raspberry Pi 4 bare metal workspace.
https://github.com/jonlamb-gh/rpi4-rust-workspace

### CODE REVIEW

**Comment by andre-richter** [comment]
For personal interest:
This looks very similar to the widespread tock-register-interface, which we also reuse I register-rs internally here.

How does this one differ from tock?

**Comment by jonlamb-gh** [comment]
It's intentionally very similar to the tock-register-interface; with the addition of type-based bounds checking.
The author, Dan, has a blog post covering some of the motivations
if interested: https://blog.auxon.io/2019/10/25/type-level-registers/

**Comment by andre-richter** [comment]
Thanks!
We have register-rs further down in the list too.
I think it could be beneficial for users to list them side-by-side and concisely explain the differences. Otherwise it's just by chance what users stumble upon first instead of making an informed decision.

Would you be up helping with that?
Register-rs is basically tock registers with added support for cpu register definition using the same API as for the MMIO ones. So for bigger projects you then have homogenous interfaces to registers of all kinds. 
So we would put that explanation, plus the differences between the bounded and tock crates.
I think tock's API has some more features as well at this point? The newly gained register block definition macro comes to my mind. Does bounded have something like InMemoryRegister too?

Best,
Andre

**Comment by jonlamb-gh** [comment]
Good idea :+1:, I'm happy to do that.
I'll take a look at the latest Tock API and push up a change to relocate the item alongside register-rs as well as some delineation between them once I'm back from holiday travels.
I don't think bounded-registers has an explicit equivalent to InMemoryRegister or register_structs macro, both would be really nice to have though.

**Pull request merged**
